In [2]:
import numpy as np

Numpy array

In [10]:
N = int(input('Введите количество чисел в массиве: '))
np.arange(0, N)[::-1]

Введите количество чисел в массиве: 15


array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

Diagonal Matrix

In [26]:
digit_amount = int(input('Введите количество чисел в матрице: '))
print(np.diag(np.arange(digit_amount, -1, -1), k=0))
print("Diagonal sum = ", np.diag(np.arange(digit_amount, -1, -1), k=0).sum())

Введите количество чисел в матрице: 9
[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
Diagonal sum =  45


the equations

4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [28]:
from numpy import linalg

In [29]:
a=np.array([[4, 2, 1], [2, 3, 1], [0, 5, 4]])
b=np.array([4, 12, -3])
linalg.solve(a, b)

array([ -0.22727273,   7.54545455, -10.18181818])

In [42]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

Similar customer

In [31]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [32]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [40]:
def similarity( row, next_user_stats ):
    
        row_length = np.linalg.norm( row )
        next_user_stats_length = np.linalg.norm( next_user_stats )
        result = np.dot( row, next_user_stats ) / ( row_length * next_user_stats_length )
        print(result, sep='\n')
                
cos_row = np.apply_along_axis(similarity, 1, users_stats, next_user_stats)

0.19999999999999996
0.8451542547285165
0.3999999999999999
0.7905694150420948
0.3999999999999999
0.0
0.0
0.9486832980505138
0.0
0.0
