# Уровень 0

In [1]:
import matplotlib.pyplot as plt
import numpy as np
from numpy import linalg as LA

In [2]:
# a) Диагональная, ортогональная, но не единичная(!)
# т.е. по диагонали искомой матрицы должны быть элементы, квадраты которых равны 1, но сами элементы не равны 1

a1 = np.array([[-1, 0, 0, 0],
               [0, -1, 0, 0],
               [0, 0, 1, 0],
               [0, 0, 0, -1]])
print(a1 @ a1.T)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


b) Верхнетреугольная, ортогональная\
c) Нижнетреугольная, ортогональная

In [5]:
# верхнетреугольная матрица — квадратная матрица, у которой все элементы ниже главной диагонали равны нулю
# нижнетреугольная матрица — квадратная матрица, у которой все элементы выше главной диагонали равны нулю 
# в обоих случаях ( и в пункте "b" и в пункте "c") можно взять матрицу из предыдущего пункта "а" - она удовлетворяет условиям.
a1 = np.array([[-1, 0, 0, 0],
               [0, -1, 0, 0],
               [0, 0, 1, 0],
               [0, 0, 0, -1]])

d) Матрица, у которой определитель = 1, и все элементы не равны 0

In [8]:
a2 =  np.array([[1, 2, 3],
                [0, 1, 4],
               [5, 6, 0]])
np.linalg.det(a2)

0.9999999999999987

Найдите собственные значения и собственные вектора матриц:

In [9]:
m = np.array([[2, 2],
              [1, 3]])
print(m)

[[2 2]
 [1 3]]


Решим уравнения:

Итак

2x + 2y = λx
x + 3y = λy
Или

(2 - λ)x + 2y = 0
x + (3 - λ)y = 0
Тогда запишем характеристическое урванение:

(2 - λ)(3 - λ) - 2 = 0
или
λ² - 5λ + 4 = 0


Корни этого уравнения: λ1 = 1 и λ2 = 4

Зная λ решаем еще несколько уравнений.
Для λ1 = 1 имеем решение y = -0.5x, тогда вектор будет (-2, 1).
Для λ2 = 4 имеем решение y = x, тогда вектор будет (1, 1).

# Уровень 1

In [11]:
# Найдите спектральное разложение матрицы:

m = np.array([[1, 2],
              [2, 3]])
print(m)

[[1 2]
 [2 3]]
